apiVersion: v1
kind: Service
metadata:
  name: cpu-service-svc
  labels:
    app: cpu-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4001
      targetPort: 4001
  selector:
    app: cpu-service
