apiVersion: v1
kind: Service
metadata:
  name: history-service-svc
  labels:
    app: history-service
spec:
  selector:
    app: history-service
  ports:
    - name: http
      port: 4004
      targetPort: 4004
