apiVersion: v1
kind: Service
metadata:
  name: rest-service-svc
  labels:
    app: rest-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: rest-service
